version: "3.3"

networks:
    login:
        driver: bridge

services:
    php:
        build: .
        ports:
            - 8080:8080
            - 80:80
        volumes:
            - ./:/var/www/html
        networks:
            - login
    mysql:
        image: mysql:5.6
        ports:
            - 3306:3306
        volumes:
            - $HOME/projects/docker/volumes/mysql:/var/lib/mysql
        networks:
            - login
        environment:
            - MYSQL_ROOT_PASSWORD=docker
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:4.9.4
        ports:
            - 8888:80
        networks:
            - login
        environment:
            - PMA_ARBITRARY=1